apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hello-server-hpa
  namespace: metrics-writer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-server
  minReplicas: 1
  maxReplicas: 30
  metrics:
  - type: External
    external:
      metric:
        name:  custom.googleapis.com|my-metric
      target:
        type: AverageValue
        averageValue: "20"